version: '3'
services:
  # app:
  #   image: idonthavespotify
  #   env_file: .env
  #   ports:
  #     - 3000:3000
  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
